// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVVO-ElnMJpWBFKRVUwIZc5zXLtmAQH4',
    appId: '1:928372581368:web:67bb351dc3f118c28fac0d',
    messagingSenderId: '928372581368',
    projectId: 'veterinaria-89de0',
    authDomain: 'veterinaria-89de0.firebaseapp.com',
    storageBucket: 'veterinaria-89de0.firebasestorage.app',
    measurementId: 'G-E6BNXNNYKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXPR0OvM891JHmEZxyC4Zk6VpJBS85Ek',
    appId: '1:928372581368:android:fe5c2db4a9169bf58fac0d',
    messagingSenderId: '928372581368',
    projectId: 'veterinaria-89de0',
    storageBucket: 'veterinaria-89de0.firebasestorage.app',
  );
}
